---

- name: change apt-cache policy
  shell: apt-cache policy docker-ce

- name: install docker-ce
  apt:
    name:
      - docker-ce
    install_recommends: yes
    state: present
    update_cache: yes

- name: copy docker network config
  copy:
    src: daemon.json
    dest: /etc/docker/
