---
  - name: установим vsftpd
    apt:
      name: vsftpd
      update_cache: no
      state: present

  - name: добавляем пользователя vsftpd
    user:
      name: ftpu01
      group: ubuntu
      shell: /bin/false
      home: /srv/ftp
      password: "qwertyuiop[]"
      state: present

  - name:  создаем каталог
    file:
      path: "/srv/ftp"
      state: directory
      owner: ftpu01
      group: ubuntu
      mode: 0770
      recurse: yes

  - name: конфиг
    blockinfile:
      path: /etc/vsftpd.conf
      create: yes
      marker: ""
      block: |
        listen=YES
        anonymous_enable=YES

  - name: restart vsftpd
    service:
      name: vsftpd
      state: restarted
